### ISSUE TITLE
Even after following the exact code, facing this error: RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 207, 13]

### ISSUE THREAD

**Issue by djshanker** [nnzhan/Graph-WaveNet#47]
(gwavenet_py310) [sshanker@hpc-login-p01 Graph-WaveNet-master]$ pip install --upgrade pip
Requirement already satisfied: pip in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (24.1.2)
Collecting pip
  Downloading pip-25.1.1-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-25.1.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Not uninstalling pip at /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages, outside environment /projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.0.1

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
(gwavenet_py310) [sshanker@hpc-login-p01 Graph-WaveNet-master]$ pip install torch torchvision
Collecting torch
  Using cached torch-2.7.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision
  Downloading torchvision-0.22.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting filelock (from torch)
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy>=1.13.3 (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Using cached fsspec-2025.5.1-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch)
  Using cached nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch)
  Using cached nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch)
  Using cached nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch)
  Using cached nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch)
  Using cached nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch)
  Using cached nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch)
  Using cached nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch)
  Using cached nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch)
  Using cached nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch)
  Using cached nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch)
  Using cached nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch)
  Using cached nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch)
  Using cached nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch)
  Using cached nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.1 (from torch)
  Using cached triton-3.3.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from triton==3.3.1->torch) (70.1.0)
Collecting numpy (from torchvision)
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 590.7 kB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Using cached torch-2.7.1-cp310-cp310-manylinux_2_28_x86_64.whl (821.2 MB)
Using cached nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
Using cached nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
Using cached nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
Using cached nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
Using cached nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
Using cached nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
Using cached nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
Using cached nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
Using cached nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
Using cached nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
Using cached nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
Using cached nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Using cached triton-3.3.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.6 MB)
Downloading torchvision-0.22.1-cp310-cp310-manylinux_2_28_x86_64.whl (7.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 10.8 MB/s eta 0:00:00
Downloading pillow-11.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 2.7 MB/s eta 0:00:00
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Downloading typing_extensions-4.14.1-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 kB 224.2 kB/s eta 0:00:00
Using cached filelock-3.18.0-py3-none-any.whl (16 kB)
Using cached fsspec-2025.5.1-py3-none-any.whl (199 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 13.2 MB/s eta 0:00:00
Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: nvidia-cusparselt-cu12, mpmath, typing-extensions, triton, sympy, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch, torchvision
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.39
    Not uninstalling nvidia-cuda-runtime-cu12 at /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages, outside environment /projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310
    Can't uninstall 'nvidia-cuda-runtime-cu12'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 7.3.7 requires requests>=2.25.0, which is not installed.
Successfully installed MarkupSafe-3.0.2 filelock-3.18.0 fsspec-2025.5.1 jinja2-3.1.6 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.6 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 pillow-11.3.0 sympy-1.14.0 torch-2.7.1 torchvision-0.22.1 triton-3.3.1 typing-extensions-4.14.1

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
(gwavenet_py310) [sshanker@hpc-login-p01 Graph-WaveNet-master]$ pip install -r requirements.txt
Collecting matplotlib (from -r requirements.txt (line 1))
  Downloading matplotlib-3.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy in ./gwavenet_py310/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.2.6)
Collecting scipy (from -r requirements.txt (line 3))
  Downloading scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.7 MB/s eta 0:00:00
Collecting pandas (from -r requirements.txt (line 4))
  Downloading pandas-2.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: torch in ./gwavenet_py310/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.7.1)
Collecting argparse (from -r requirements.txt (line 6))
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 1))
  Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 1))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements.txt (line 1))
  Downloading fonttools-4.58.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.9/106.9 kB 5.0 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirements.txt (line 1))
  Downloading kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.2 kB)
Requirement already satisfied: packaging>=20.0 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 1)) (24.1)
Requirement already satisfied: pillow>=8 in ./gwavenet_py310/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 1)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 1)) (3.1.2)
Collecting python-dateutil>=2.7 (from matplotlib->-r requirements.txt (line 1))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: pytz>=2020.1 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 4)) (2024.1)
Collecting tzdata>=2022.7 (from pandas->-r requirements.txt (line 4))
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: filelock in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: networkx in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (3.4.2)
Requirement already satisfied: jinja2 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: fsspec in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.6.77)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch->-r requirements.txt (line 5))
  Using cached nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in ./gwavenet_py310/lib/python3.10/site-packages (from torch->-r requirements.txt (line 5)) (3.3.1)
Requirement already satisfied: setuptools>=40.8.0 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from triton==3.3.1->torch->-r requirements.txt (line 5)) (70.1.0)
Requirement already satisfied: six>=1.5 in /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./gwavenet_py310/lib/python3.10/site-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./gwavenet_py310/lib/python3.10/site-packages (from jinja2->torch->-r requirements.txt (line 5)) (3.0.2)
Downloading matplotlib-3.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 11.6 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 15.2 MB/s eta 0:00:00
Downloading pandas-2.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 4.4 MB/s eta 0:00:00
Using cached nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Downloading contourpy-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (325 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.0/325.0 kB 3.7 MB/s eta 0:00:00
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.58.5-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 9.1 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.2 MB/s eta 0:00:00
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: argparse, tzdata, scipy, python-dateutil, nvidia-cuda-runtime-cu12, kiwisolver, fonttools, cycler, contourpy, pandas, matplotlib
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.39
    Not uninstalling nvidia-cuda-runtime-cu12 at /cm/shared/apps/Python/3.10.14/lib/python3.10/site-packages, outside environment /projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310
    Can't uninstall 'nvidia-cuda-runtime-cu12'. No files were found to uninstall.
Successfully installed argparse-1.4.0 contourpy-1.3.2 cycler-0.12.1 fonttools-4.58.5 kiwisolver-1.4.8 matplotlib-3.10.3 nvidia-cuda-runtime-cu12-12.6.77 pandas-2.3.1 python-dateutil-2.9.0.post0 scipy-1.15.3 tzdata-2025.2

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
(gwavenet_py310) [sshanker@hpc-login-p01 Graph-WaveNet-master]$ python train.py --device cpu --data data/METR-LA --adjdata data/sensor_graph/adj_mx_METR-LA.pkl --num_nodes 207 --save 1 --epochs 50
Namespace(device='cpu', data='data/METR-LA', adjdata='data/sensor_graph/adj_mx_METR-LA.pkl', adjtype='doubletransition', gcn_bool=False, aptonly=False, addaptadj=False, randomadj=False, seq_length=12, nhid=32, in_dim=2, num_nodes=207, batch_size=64, learning_rate=0.001, dropout=0.3, weight_decay=0.0001, epochs=50, print_every=50, save='1', expid=1)
start training...
Traceback (most recent call last):
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/train.py", line 173, in <module>
    main()
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/train.py", line 84, in main
    metrics = engine.train(trainx, trainy[:,0,:,:])
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/engine.py", line 17, in train
    output = self.model(input)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/model.py", line 175, in forward
    gate = self.gate_convs[i](residual)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 375, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/projects/geo-data-science-lab/Graph-WaveNet-master/Graph-WaveNet-master/gwavenet_py310/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 370, in _conv_forward
    return F.conv1d(
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 207, 13]
(gwavenet_py310) [sshanker@hpc-login-p01 Graph-WaveNet-master]$ client_loop: send disconnect: Connection reset

**Comment by Zach-ceng** [comment]
I meet the same problem

**Comment by Zach-ceng** [comment]
changing all of the nn.Conv1d into nn.Conv2d in model.py can fix the problem, it seems to be related to the update of the versions.

**Comment by BraydenJamesE** [comment]
> changing all of the nn.Conv1d into nn.Conv2d in model.py can fix the problem, it seems to be related to the update of the versions.

Thank you so much; this fixed it for me!

**Comment by gcalistanford** [comment]
@BraydenJamesE  Hi I am also struggling with this issue. Did you implement the changes recommended and did it work???? I am specifically trying to use GWN with Captum's Integrated Gradients and this issue of size kept coming up. I just don't want to reduce the performance of the model with changes like this if they are dramatic. 

@Zach-ceng To your understanding is this change dramatic to the model's capability ?

**Comment by Zach-ceng** [comment]
@gcalistanford  After my experiment, it did not significantly affect the performance of the model

**Comment by gcalistanford** [comment]
@Zach-ceng Thank you Zach! This is helpful to hear.  Is your data multi-features as well? Also, have you perhaps used any explainers like Integrated Gradients on the model? Appreciate this response. It is very reassuring.

**Comment by Zach-ceng** [comment]
@gcalistanford  I conducted experiments on four datasets: PEMS08, PEMS04, PEMSBay, and metr-la. Unfortunately, I did not use any interpreter to explain them. Hope you doing well
